version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TuPassword123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - ombu-network

  redis:
    image: redis:7-alpine
    container_name: ombu-redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ombu-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ombu-rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"     # Puerto estándar AMQP 0-9-1
      - "15672:15672"   # Panel Web de Gestión (RabbitMQ Management Dashboard)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ombu-network

volumes:
  mssql_data:
  redis_data:
  rabbitmq_data:

networks:
  ombu-network:
    driver: bridge
